apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T11:37:14Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "49309"
  uid: 845055fb-9e55-4f5d-ace3-6a557c2f91a9
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.99.57.216
  clusterIPs:
  - 10.99.57.216
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30371
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
